# Generated by Django 4.0.2 on 2022-03-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20220225_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='URL',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
